[package]
name = "subkey"
version = "2.0.1"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = ""
repository = "https://github.com/axia-tech/substrate/"
readme = "README.md"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
path = "src/main.rs"
name = "subkey"

[dependencies]
sc-cli = { version = "0.10.0-dev", path = "../../../client/cli" }
structopt = "0.3.14"
