[package]
name = "node-rpc-client"
version = "2.0.0"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.17"
jsonrpc-core-client = { version = "18.0.0", default-features = false, features = [
    "http",
] }
node-primitives = { version = "2.0.0", path = "../primitives" }
sp-tracing = { version = "4.0.0-dev", path = "../../../primitives/tracing" }
sc-rpc = { version = "4.0.0-dev", path = "../../../client/rpc" }
